In [5]:
import numpy as np

In [2]:
from time import process_time

In [3]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0


In [7]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array +=5
end_time=process_time()
print(end_time-start_time)

0.0


In [9]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [10]:
b=np.array([(1,2,3,4),(5,6,7,8)],)
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b.shape

(2, 4)

In [13]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [15]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [18]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
import numpy as np
list=[10,20,30,40,50]
np_array=np.asarray(list)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [4]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[1 2 3]
 [7 9 8]
 [8 2 8]]
[[10 15 13]
 [10 12 17]
 [15 10 14]]


In [7]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[11 17 16]
 [17 21 25]
 [23 12 22]]
[[ -9 -13 -10]
 [ -3  -3  -9]
 [ -7  -8  -6]]
[[ 10  30  39]
 [ 70 108 136]
 [120  20 112]]
[[0.1        0.13333333 0.23076923]
 [0.7        0.75       0.47058824]
 [0.53333333 0.2        0.57142857]]


In [9]:
#rephrasing an array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 1 6]
 [7 3 1]]
(2, 3)


In [10]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[4 1]
 [6 7]
 [3 1]]
(3, 2)


In [13]:
x=np.linspace(0,10,5)#5 evenly spaces values between 0 and 10
y=np.sin(x)
z=np.cos(x)
print(x)

[ 0.   2.5  5.   7.5 10. ]
